### ISSUE TITLE
Peer-to-peer review for book app

### ISSUE THREAD

**Issue by mohashyne** [pulgosodog/awesome-books#2]
# requested   changes

- [ ] It will be nice if you use  html semantic by using  (ul > li ) for the book title  and book author  instead of h2 for all book properties.
- [ ] kindly consider to re-arrange all your called items/elements in JavaScript from html at the top.

You have  really done a create  great job , but kindly put this into consideration.

**Comment by pulgosodog** [comment]
Implemented `<ul>` and `<li>` tags
